import CheckinCheckoutTimesModelInterface from 'modules/hotel/models/CheckinCheckoutTimesModel/CheckinCheckoutTimesModelInterface';
import HotelFacilitiesModelInterface from 'modules/hotel/models/HotelFacilitiesModel/HotelFacilitiesModelInterface';
import HotelPhotoModelInterface from 'modules/hotel/models/HotelPhotoModel/HotelPhotoModelInterface';
import PopularPocilitiesModelInterface from 'modules/hotel/models/PopularPocilitiesModel/PopularPocilitiesModelInterface';
import LocationModel from 'modules/hotel/models/LocationModel';
import PaymentOptionsModelInterface from 'modules/hotel/models/PaymentOptionsModel/PaymentOptionsModelInterface';
import PaymentDetailsModelInterface from 'modules/hotel/models/PaymentDetailsModel/PaymentDetailsModelInterface';
import NearByLocationModelInterface from 'modules/hotel/models/NearByLocationModel/NearByLocationModelInterface';
import HotelPoliciesModelInterface from 'modules/hotel/models/HotelPoliciesModel/HotelPoliciesModelInterface';

export default interface HotelInfoModelInterface {
    address: string;
    checkinCheckoutTimes: CheckinCheckoutTimesModelInterface;
    city: string;
    cityId: number;
    class: number;
    classIsEstimated: boolean;
    country: string;
    creditcardRequired: boolean;
    currency: string;
    defaultLanguage: string;
    exactClass: number;
    hotelDescription: string;
    hotelFacilities: HotelFacilitiesModelInterface[];
    hotelImportantInformation: string;
    hotelPhotos: HotelPhotoModelInterface[]; 
    hotelPolicies: HotelPoliciesModelInterface[];
    hotelPopularPolicies: PopularPocilitiesModelInterface;
    hotelTypeId: number;
    isClosed: boolean;
    location: LocationModel;
    name: string;
    nearByLocation: NearByLocationModelInterface;
    paymentDetails: PaymentDetailsModelInterface[];
    paymentOptions: PaymentOptionsModelInterface;
    ranking: number;
    spokenLanguages: string[];
    themeIds: number[];
    zip: string;
}